name: Test model compilation

on:
  push:
    branches: ['main']
  pull_request:

env:
  SONATA_REPORT_VERSION: '2.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        python -m pip install NEURON-nightly

    - name: Build and install models
      run: |
        nrnivmodl -coreneuron ${{ github.workspace }}/common/mod

    - name: Quick test to load models
      run: |
        ./${{ github.workspace }}/x86_64/special -python -c "from neuron import h; h.quit()"
